[package]
name = "workfile-backupper"
version = "0.1.0"
description = "A Tauri App"
authors = ["Kobayashi Kenji"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
# The `_lib` suffix may seem redundant but it is necessary
# to make the lib name unique and wouldn't conflict with the bin name.
# This seems to be only an issue on Windows, see https://github.com/rust-lang/cargo/issues/8519
name = "workfile_backupper_lib"
crate-type = ["staticlib", "cdylib", "rlib"]

[build-dependencies]
tauri-build = { version = "2", features = [] }

[dependencies]
tauri = { version = "2", features = [ "tray-icon" ] }
tauri-plugin-opener = "2"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
tauri-plugin-notification = "2"
chrono = "0.4.44"
tokio = { version = "1.52.3", features = ["full"] }
futures = "0.3.32"
notify-debouncer-full = "0.7.0"
tauri-plugin-single-instance = "2.4.2"
tauri-plugin-dialog = "2"
tempfile = "3"
ts-rs = { version = "12.0.1", features = ["format"] }

