// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * 通知範囲
 */
export type NotifyRange = "dialog" | "desktop" | "log" | "console" | "none";
